[package]
name = "vtc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
nom = "7.1.3"
serde = "1.0.210"
thiserror = "1.0.63"
