[package]
name = "vtc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
nom = "7.1.3"
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.63"
smallvec = "1.10.0"
string_cache = "0.8"

[dev-dependencies]
criterion = "0.5.1"
proptest = "1.0"
insta = "1.26"

[[bench]]
name = "vtc_benchmarks"
harness = false

[profile.release]
lto = true
codegen-units = 1
panic = "abort"